version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=valas
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 33306:3306
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
  myapp:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=valas
    depends_on:
      - mysql
